### PR TITLE
Cache proto ByteString in server reflection (#1528)

### PR DESCRIPTION
**Pull request by github-samuel-clarenc**
References #1528

This PR adds a simple cache to the proto to bytes method in ServerReflection. 

The unit tests are completed in this PR but we can't really test whether the cache is actually used or not.

### CODE REVIEW

File: runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala [hunk 1]
```diff
@@ -52,6 +55,9 @@ final class ServerReflectionImpl private (fileDescriptors: Map[String, FileDescr
       ServerReflectionResponse(req.host, Some(req), response)
     })
   }
+
+  private def getProtoBytes(fileDescriptor: FileDescriptor): ByteString =
+    protoBytesLocalCache.getOrElseUpdate(fileDescriptor.getName, fileDescriptor.toProto.toByteString)
```
Comment (raboof) [inline runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:60]: I think this isn't thread-safe, is it? Might be worth picking a concurrent implementation, perhaps even just good old `ConcurrentHashMap`

**Review by raboof — COMMENTED** [review]
Looks good, thanks for also extending the tests. One comment for consideration, otherwise LGTM!

File: runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala (hunk 1 above)
Comment (github-samuel-clarenc) [reply runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:60]: Indeed it's not thread safe this way, I'll make the change !

Comment (github-samuel-clarenc) [reply runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:63]: Done !

**Review by raboof — APPROVED** [review]
Nice one, thanks!

**Comment by raboof** [comment]
Ah, it looks like it doesn't compile on Scala 2.13 though:
```
[error] /home/runner/work/akka-grpc/akka-grpc/runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:16:8: value mapAsScalaConcurrentMapConverter is not a member of object scala.jdk.CollectionConverters
[error] import scala.jdk.CollectionConverters.mapAsScalaConcurrentMapConverter
[error]        ^
[error] /home/runner/work/akka-grpc/akka-grpc/runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:27:49: value asScala is not a member of java.util.concurrent.ConcurrentHashMap[String,com.google.protobuf.ByteString]
[error]     new ConcurrentHashMap[String, ByteString]().asScala
```

**Comment by github-samuel-clarenc** [comment]
> Ah, it looks like it doesn't compile on Scala 2.13 though:
> 
> ```
> [error] /home/runner/work/akka-grpc/akka-grpc/runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:16:8: value mapAsScalaConcurrentMapConverter is not a member of object scala.jdk.CollectionConverters
> [error] import scala.jdk.CollectionConverters.mapAsScalaConcurrentMapConverter
> [error]        ^
> [error] /home/runner/work/akka-grpc/akka-grpc/runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala:27:49: value asScala is not a member of java.util.concurrent.ConcurrentHashMap[String,com.google.protobuf.ByteString]
> [error]     new ConcurrentHashMap[String, ByteString]().asScala
> ```

:scream: 

I changed the collection converter to `collection.JavaConverters._` which seems to work for both 2.12 and 2.13 !

**Comment by raboof** [comment]
> I changed the collection converter to `collection.JavaConverters._` which seems to work for both 2.12 and 2.13 !

Jep, looks like that did the trick! Thanks!
